# ExyliaStaff - Configuración Principal

debug: false
database:
  type: sqlite
  sqlite:
    file_name: exylia_staff.db
  mysql:
    host: localhost
    port: 3306
    database: exylia_staff
    username: exylia_staff
    password: exylia_staff

aliases:
  staff_mode: ["staffmode", "staff", "mod"]
  vanish: ["vanish", "v"]

staff-mode:
  gamemode: CREATIVE
  can-break-blocks: false
  can-place-blocks: false
  can-damage-entities: false
  phase-distance: 100

miner-hub:
  min-height: 10

prefixes:
  staff-mode: "<#ffc58f>Staff <dark_gray><bold>•<reset> <#ffd2a8>"
  frozen: "<#ffc58f>SS <dark_gray><bold>•<reset> <#ffd2a8>"
  vanish: "<#ffc58f>V <dark_gray><bold>•<reset> <#ffd2a8>"

frozen:
  allowed-commands:
    - /msg
    - /r
    - /tell
  task_delay: 100 # in ticks
  sound:
    enabled: true
    sound: BLOCK_AMETHYST_CLUSTER_BREAK|0.2|0.4
  effects:
    enabled: true
    effects:
      - GLOWING|1|100
      - BLINDNESS|1|100
      - DARKNESS|1|100
  commands-on-disconnect:
    enabled: true
    console_commands:
      - "/say %player% disconnected in frozen mode"
    staff_commands:
      - "/ban %player% 14d Desconectarse en SS"

# Configuración de los ítems de modo staff
staff-items:
  teleport:
    material: CLOCK
    display-name: "<#b48fd9>• <#8a51c4>ᴛᴇʟᴇᴛʀᴀɴsᴘᴏʀᴛᴇ"
    lore:
      - "&7Right-click to teleport to the target block"
      - "&7Left-click on a player to teleport to them"
    glow: false
    action: phase
    slot: 0

  freeze:
    material: PACKED_ICE
    display-name: "<#b48fd9>• <#8a51c4>ᴄᴏɴɢᴇʟᴀʀ ᴊᴜɢᴀᴅᴏʀ"
    lore:
      - "&7Right-click on a player to freeze/unfreeze them"
    glow: false
    action: freeze
    slot: 1

  inspect:
    material: BOOK
    display-name: "<#b48fd9>• <#8a51c4>ᴠᴇʀ ɪɴᴠᴇɴᴛᴀʀɪᴏ"
    lore:
      - "&7Right-click on a player to inspect their inventory"
    glow: false
    action: inspect
    slot: 4

  miner_hub:
    material: GOLDEN_PICKAXE
    display-name: "<#b48fd9>• <#8a51c4>ᴄᴇɴᴛʀᴏ ᴍɪɴᴇʀᴏ"
    lore:
      - "&7Right-click to open the miner hub"
    glow: false
    action: miner_hub
    slot: 6

  random_player_tp:
    material: MUSIC_DISC_13
    display-name: "<#b48fd9>• <#8a51c4>ᴛᴇʟᴇᴛʀᴀɴsᴘᴏʀᴛᴇ ᴀʟᴇᴀᴛᴏʀɪᴏ"
    lore:
      - "&7Right-click to teleport to a random player"
    glow: false
    action: random_player_tp
    slot: 7

  vanish:
    material: GRAY_DYE
    display-name: "<#FF0000>❌ ɪɴᴠɪsɪʙɪʟɪᴅᴀᴅ"
    lore:
      - "&7Right-click to enable vanish mode"
    glow: true
    action: vanish
    slot: 8
    un-vanish:
      material: LIME_DYE
      display-name: "<#8fffc1>✔ ɪɴᴠɪsɪʙɪʟɪᴅᴀᴅ"
      lore:
        - "&7Right-click to disable vanish mode"
      glow: true
      action: un_vanish
      slot: 8

staff-scoreboard:
  enabled: true
  title: "&6Staff Mode"
  lines:
    - "&7Players: %players%"
    - "&7Commands: %commands%"

staff-bossbars:
  enabled: true
  example:
    title: "&6Staff Mode"
    color: BLUE
    progress: 0
    style: PROGRESS

staff-notifications:
  block-break:
    enabled: true
    sound: BLOCK_AMETHYST_CLUSTER_BREAK|0.5|1.0
    blocks:
      - DIAMOND_ORE|&#7db7ff
      - DEEPSLATE_DIAMOND_ORE|&#59a4ff
      - ANCIENT_DEBRIS|&#ffc58f