debug: false
server-name: SurvivalPvP

database:
  type: sqlite
  sqlite:
    file_name: exylia_staff.db
  mysql:
    host: localhost
    port: 3306
    database: exylia_staff
    username: exylia_staff
    password: exylia_staff

prefixes:
  staff-mode: "<#59a4ff>Staff <dark_gray><bold>•<reset><#59a4ff>"
  frozen: "<#aa76de>SS <dark_gray><bold>•<reset><#aa76de>"
  vanish: "<#a1ffc3>V <dark_gray><bold>•<reset><#a1ffc3>"

aliases:
  staff_mode: ["staffmode", "staff", "mod"]
  vanish: ["vanish", "v"]
  notifications: ["staff-notifications", "mine-alerts"]
  freeze: ["freeze", "ss"]
  punish: ["punish", "punishment"]

modules:
  staff-mode: true
  notifications: true
  freeze: true
  scoreboard: true
  staff-chat: true
  vanish: true
  punish: true