# ExyliaStaff - Configuración Principal

# Modo debug (mensajes extra en la consola)
debug: true

# Configuración de la base de datos
database:
  type: sqlite
  sqlite:
    file_name: exylia_staff.db
  mysql:
    host: localhost
    port: 3306
    database: exylia_staff
    username: exylia_staff
    password: exylia_staff

prefixes:
  staff-mode: "<#59a4ff>Staff <dark_gray><bold>•<reset><#59a4ff>"
  frozen: "<#aa76de>SS <dark_gray><bold>•<reset><#aa76de>"
  vanish: "<#a1ffc3>V <dark_gray><bold>•<reset><#a1ffc3>"

aliases:
  staff_mode: ["staffmode", "staff", "mod"]
  vanish: ["vanish", "v"]
  notifications: ["staff-notifications", "mine-alerts"]
  freeze: ["freeze", "ss"]
  punish: ["punish", "punishment"]

staff-mode:
  gamemode: ADVENTURE
  can-break-blocks: false
  can-place-blocks: false
  can-damage-entities: false
  phase-distance: 100
  effects:
    - NIGHT_VISION|1|-1
    - SPEED|2|-1

frozen:
  allowed-commands:
    - msg
    - r
    - tell
  task_delay: 100
  sound:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_CHIME|1.0|1.0
  effects:
    enabled: true
    effects:
      - GLOWING|1|110
      - BLINDNESS|1|110
      - DARKNESS|1|110
  commands-on-disconnect:
    enabled: true
    commands:
      - "bungee: as_player:ban %player_name% disconnect_in_ss server:global"

# Configuración de los ítems de modo staff
staff-items:
  teleport:
    material: CLOCK
    display-name: "<#b48fd9>• <#8a51c4>ᴛᴇʟᴇᴛʀᴀɴsᴘᴏʀᴛᴇ"
    lore:
      - "&7Haz clic derecho para teletransportarte al bloque objetivo"
      - "&7Haz clic izquierdo sobre un jugador para teletransportarte a él"
    glow: false
    action: phase
    slot: 0

  vanish:
    material: GRAY_DYE
    display-name: "<#FF0000>❌ ɪɴᴠɪsɪʙɪʟɪᴅᴀᴅ"
    lore:
      - "&7Haz clic derecho para activar el modo invisible"
    glow: true
    action: vanish
    slot: 8
    un-vanish:
      material: LIME_DYE
      display-name: "<#8fffc1>✔ ɪɴᴠɪsɪʙɪʟɪᴅᴀᴅ"
      lore:
        - "&7Haz clic derecho para desactivar el modo invisible"
      glow: true
      action: un_vanish
      slot: 8

  freeze:
    material: PACKED_ICE
    display-name: "<#b48fd9>• <#8a51c4>ᴄᴏɴɢᴇʟᴀʀ ᴊᴜɢᴀᴅᴏʀ"
    lore:
      - "&7Haz clic derecho sobre un jugador para congelarlo o descongelarlo"
    glow: false
    action: freeze
    slot: 1

  punish:
    material: MACE
    display-name: "<#b48fd9>• <#8a51c4>sᴀɴᴄɪᴏɴᴀʀ ᴊᴜɢᴀᴅᴏʀ"
    lore:
      - "&7Haz clic sobre un jugador para sancionarlo"
    glow: false
    action: punish_menu
    slot: 2

  coreprotect:
    material: FIELD_MASONED_BANNER_PATTERN
    display-name: "<#b48fd9>• <#8a51c4>ᴀʟᴛᴇʀɴᴀʀ ɪɴsᴘᴇᴄᴛᴏʀ"
    lore:
      - "&7Clic para alternar el inspector"
    glow: false
    action: commands
    slot: 9
    commands:
      - "player: co i"

  notify:
    material: BORDURE_INDENTED_BANNER_PATTERN
    display-name: "<#b48fd9>• <#8a51c4>ᴀʟᴛᴇʀɴᴀʀ ɴᴏᴛɪғɪᴄᴀᴄɪᴏɴᴇs"
    lore:
      - "&7Clic para alternar notificaciones"
    glow: false
    action: commands
    slot: 10
    commands:
      - "player: staff-notifications"

  exit:
    material: STRUCTURE_VOID
    display-name: "<#b48fd9>• <#8fffc1>sᴀʟɪʀ ᴅᴇʟ ᴍᴏᴅᴏ sᴛᴀғғ"
    lore:
      - "&7Clic para salir del modo staff"
    glow: false
    action: exit
    slot: 17

  inspect:
    material: BOOK
    display-name: "<#b48fd9>• <#8a51c4>ᴠᴇʀ ɪɴᴠᴇɴᴛᴀʀɪᴏ"
    lore:
      - "&7Haz clic derecho sobre un jugador para ver su inventario"
    glow: false
    action: inspect
    slot: 4

  toggle_spectator:
    material: GLOW_INK_SAC
    display-name: "<#b48fd9>• <#8a51c4>ᴀʟᴛᴇʀɴᴀʀ ᴍᴏᴅᴏ ᴇꜱᴘᴇᴄᴛᴀᴅᴏʀ"
    lore:
      - "&7Haz clic para alternar el modo de juego."
    glow: false
    action: toggle_spectator
    slot: 27

  miner_hub:
    material: GOLDEN_PICKAXE
    display-name: "<#b48fd9>• <#8a51c4>ᴄᴇɴᴛʀᴏ ᴍɪɴᴇʀᴏ"
    lore:
      - "&7Clic para abrir el centro minero"
    glow: false
    action: miner_hub
    slot: 35

  checker:
    material: RECOVERY_COMPASS
    display-name: "<#b48fd9>• <#8a51c4>ᴍᴜʟᴛɪꜱ ʏ ʜɪꜱᴛᴏʀɪᴀʟ"
    lore:
      - "&7Haz clic derecho a un jugador para ver información"
    glow: false
    action: commands
    slot: 6
    commands:
      - "bungee: as_player:checkalts %target%"
      - "bungee: as_player:history %target%"

  random_player_tp:
    material: MUSIC_DISC_13
    display-name: "<#b48fd9>• <#8a51c4>ᴛᴇʟᴇᴛʀᴀɴsᴘᴏʀᴛᴇ ᴀʟᴇᴀᴛᴏʀɪᴏ"
    lore:
      - "&7Haz clic derecho para teletransportarte a un jugador aleatorio"
    glow: false
    action: random_player_tp
    slot: 7

staff-scoreboard:
  enabled: true
  update-interval: 20
  title: "&#8a51c4&lMODO STAFF"
  lines:
    - "&f"
    - "<#ffc58f>Staff"
    - "<#ffc58f> | &fInvisibilidad: <#ffc58f>%exyliastaff_status_vanish%"
    - "<#ffc58f> | &fNotificaciones: <#ffc58f>%exyliastaff_status_notifications%"
    - "<#ffc58f> | &fStaff Activo: <#ffc58f>%exyliastaff_online_staff%"
    - "&f"
    - "<#59a4ff>Servidor"
    - "<#59a4ff> | &fTPS: <#59a4ff>%kyorify_spark_tps_5s%"
    - "<#59a4ff> | &fMSPT: <#59a4ff>%kyorify_spark_tickduration_10s%"
    - "<#59a4ff> | &fSys CPU: <#59a4ff>%kyorify_spark_cpu_system_10s%"
    - "<#59a4ff> | &fProc CPU: <#59a4ff>%kyorify_spark_cpu_process_10s%"
    - "<#59a4ff> | &fPing: <#59a4ff>%player_ping%ms"
    - "<#59a4ff> | &fConectados: <#59a4ff>%server_online%&8/<#59a4ff>%server_max_players%"
    - "&f"

staff-bossbars:
  enabled: true
  example:
    title: "&6Staff Mode"
    color: BLUE
    progress: 0
    style: PROGRESS

staff-notifications:
  block-break:
    enabled: true
    sound: BLOCK_AMETHYST_CLUSTER_BREAK|0.2|0.4
    blocks:
      - DIAMOND_ORE|&#7db7ff
      - DEEPSLATE_DIAMOND_ORE|&#59a4ff
      - ANCIENT_DEBRIS|&#ffc58f