# ExyliaStaff - Configuración Principal

# Modo debug (mensajes extra en la consola)
debug: true

# Configuración de la base de datos
database:
  type: sqlite
  sqlite:
    file_name: exylia_staff.db
  mysql:
    host: localhost
    port: 3306
    database: exylia_staff
    username: exylia_staff
    password: exylia_staff

prefixes:
  staff-mode: "<#59a4ff>Staff <dark_gray><bold>•<reset><#59a4ff>"
  frozen: "<#aa76de>SS <dark_gray><bold>•<reset><#aa76de>"
  vanish: "<#a1ffc3>V <dark_gray><bold>•<reset><#a1ffc3>"

aliases:
  staff_mode: ["staffmode", "staff", "mod"]
  vanish: ["vanish", "v"]
  notifications: ["mine-alerts", "staff-notifications"]

staff-mode:
  gamemode: CREATIVE

  can-break-blocks: false
  can-place-blocks: false
  can-damage-entities: false
  phase-distance: 100

frozen:
  allowed-commands:
    - /msg
    - /r
    - /tell
  task_delay: 100
  sound:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_CHIME|1.0|1.0
  effects:
    enabled: true
    effects:
      - GLOWING|1|100
      - BLINDNESS|1|100
      - DARKNESS|1|100
  commands-on-disconnect:
    enabled: true
    console_commands:
      - "/say %player% disconnected in frozen mode"
    staff_commands:
      - "/ban %player% 14d Desconectarse en SS"

# Configuración de los ítems de modo staff
staff-items:
  teleport:
    material: CLOCK
    display-name: "<#b48fd9>• <#8a51c4>ᴛᴇʟᴇᴛʀᴀɴsᴘᴏʀᴛᴇ"
    lore:
      - "&7Right-click to teleport to the target block"
      - "&7Left-click on a player to teleport to them"
    glow: false
    action: phase
    slot: 0

  vanish:
    material: GRAY_DYE
    display-name: "<#FF0000>❌ ɪɴᴠɪsɪʙɪʟɪᴅᴀᴅ"
    lore:
      - "&7Right-click to enable vanish mode"
    glow: true
    action: vanish
    slot: 8
    un-vanish:
      material: LIME_DYE
      display-name: "<#8fffc1>✔ ɪɴᴠɪsɪʙɪʟɪᴅᴀᴅ"
      lore:
        - "&7Right-click to disable vanish mode"
      glow: true
      action: un_vanish
      slot: 8

  freeze:
    material: PACKED_ICE
    display-name: "<#b48fd9>• <#8a51c4>ᴄᴏɴɢᴇʟᴀʀ ᴊᴜɢᴀᴅᴏʀ"
    lore:
      - "&7Right-click on a player to freeze/unfreeze them"
    glow: false
    action: freeze
    slot: 1

  inspect:
    material: BOOK
    display-name: "<#b48fd9>• <#8a51c4>ᴠᴇʀ ɪɴᴠᴇɴᴛᴀʀɪᴏ"
    lore:
      - "&7Right-click on a player to inspect their inventory"
    glow: false
    action: inspect
    slot: 4

  miner_hub:
    material: GOLDEN_PICKAXE
    display-name: "<#b48fd9>• <#8a51c4>ᴄᴇɴᴛʀᴏ ᴍɪɴᴇʀᴏ"
    lore:
      - "&7Right-click to open the miner hub"
    glow: false
    action: miner_hub
    slot: 6

  random_player_tp:
    material: MUSIC_DISC_13
    display-name: "<#b48fd9>• <#8a51c4>ᴛᴇʟᴇᴛʀᴀɴsᴘᴏʀᴛᴇ ᴀʟᴇᴀᴛᴏʀɪᴏ"
    lore:
      - "&7Right-click to teleport to a random player"
    glow: false
    action: random_player_tp
    slot: 7

staff-scoreboard:
  enabled: true
  update-interval: 20
  title: "&#8a51c4&lMODO STAFF"
  lines:
    - "&f"
    - "<#ffc58f>Staff"
    - "<#ffc58f> | &fVanish: <#ffc58f>%exyliastaff_status_vanish%"
    - "<#ffc58f> | &fNotifications: <#ffc58f>%exyliastaff_status_notifications%"
    - "<#ffc58f> | &fStaff Activo: <#ffc58f>%exyliastaff_online_staff%"
    - "&f"
    - "<#59a4ff>Servidor"
    - "<#59a4ff> | &fTPS: <#59a4ff>%kyorify_spark_tps_5s%"
    - "<#59a4ff> | &fMSPT: <#59a4ff>%kyorify_spark_tickduration_10s%"
    - "<#59a4ff> | &fSys CPU: <#59a4ff>%kyorify_spark_cpu_system_10s%"
    - "<#59a4ff> | &fProc CPU: <#59a4ff>%kyorify_spark_cpu_process_10s%"
    - "<#59a4ff> | &fPing: <#59a4ff>%player_ping%ms"
    - "<#59a4ff> | &fConectados: <#59a4ff>%server_online%&8/<#59a4ff>%server_max_players%"
    - "&f"

staff-bossbars:
  enabled: true
  example:
    title: "&6Staff Mode"
    color: BLUE
    progress: 0
    style: PROGRESS

staff-notifications:
  block-break:
    enabled: true
    sound: BLOCK_AMETHYST_CLUSTER_BREAK|0.2|0.4
    blocks:
      - DIAMOND_ORE|&#7db7ff
      - DEEPSLATE_DIAMOND_ORE|&#59a4ff
      - ANCIENT_DEBRIS|&#ffc58f