name: ExyliaStaff
version: '1.0-SNAPSHOT'
main: net.exylia.exyliaStaff.ExyliaStaff
api-version: '1.18'
author: DiGround
website: https://discord.gg/85qjmgK2NS
softdepend: [PlaceholderAPI]

libraries:
  - 'com.zaxxer:HikariCP:5.1.0'
  - 'org.xerial:sqlite-jdbc:3.45.2.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.4'